### ISSUE TITLE
`API` doesn't subclass `object`

### ISSUE THREAD

**Issue by sesas** [veox/python2-krakenex#1]
Hi, I was trying to subclass `krakenex.api.API` but I got errors caused by the fact that `API` doesn't subclass from `object`, so I thought of posting this issue here.

The change would be minimal:
from 
`class API:`
to
`class API(object):`

Cheers, 
Gabriel

**Comment by veox** [comment]
Thanks!

**Comment by sesas** [comment]
:+1:
