### ISSUE TITLE
Get ticker data for all currencies

### ISSUE THREAD

**Issue by hunsnowboarder** [veox/python2-krakenex#3]
Hi! Thank you so much for this python wrapper. I am very new into APIs, so probably i am doing wrong something.

I am trying to get all the public ticker data for a LIST of currencies. I use the command:
```
coin_order_list = [{"pair": 'XETHXXBT'}, {"pair": 'XXMRXXBT'}]
k_query = k.query_public('Ticker',coin_order_list )

```
But I get error. 
If i use:
`k_query = k.query_public('Ticker', {"pair": 'XETHXXBT', "pair": 'XXMRXXBT'})`
Then I get only the results for the last currency.
Could you please help me how to get the results for a list of currencies?
Thank you very much in advance!

**Comment by veox** [comment]
The Python 2 package is unmaintained. The repo is for historic purposes only.

Do try the [Python 3 version](https://github.com/veox/python3-krakenex).

-----

As to your question, [Kraken's API docs](https://www.kraken.com/help/api#get-ticker-info) state:

> pair = comma delimited list of asset pairs to get info on

So, do:

``` python
k.query_public('Ticker', {'pair': 'XETHXXBT,XXMRXXBT'})
```

Or, perhaps:

``` python
pair_list = ['XETHXXBT', 'XXMRXXBT']
k.query_public('Ticker', {'pair': ','.join(pair_list)})
```
